name: release

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11']
        django: ['3.2', '4.2', '5.0']
        include:
          - python-version: '3.12'
            django: '5.0'

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/test
      with:
        python-version: ${{ matrix.python-version }}
        django-version: ${{ matrix.django }}

  release:
    runs-on: ubuntu-latest
    needs: [test]
    environment: release
    permissions:
      id-token: write
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: build
      run: ./run.sh build

    - name: check
      run: ./run.sh check

    - name: release
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
